# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
git:
  submodules:
    false
before_install:
  - echo -e "machine github.com\n  login ci-user\n  password $GITHUB_PAT" >~/.netrc
  - git submodule update --init --recursive
r_github_packages:
  - mrc-ide/first90
  - andrewsali/shinycssloaders
r_packages:
  - tidyr
  - numDeriv
  - shiny
  - shinyjs
  - glue
  - devtools
  - purrr
  - rhandsontable
  - data.table
  - ggplot2
  - memoise
  - httr
  - RSelenium
  - testthat
  - R.utils
jobs:
  include:
    - stage: test
      script: ./scripts/test
