# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
git:
  submodules:
    false
before_install:
  - git clone https://$github_pat@github.com/mrc-ide/shiny90_sample_files sample_files
  - echo $github_pat > github_token
install:
  - ./scripts/bootstrap
  - ./scripts/bootstrap-dev.R
  - ./scripts/install_geckodriver.sh
script: ./scripts/test
cache:
  directories:
    - shiny90/packages
