version: 2
jobs:
  build:
    docker:
      - image: rocker/verse:latest
    steps:
        # Allows us to issue docker commands from within the build container
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.06.1-ce"
            wget -O /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - checkout
      - restore_cache:
          keys:
            - R-{{ checksum "bootstrap.R" }}
            - R- # used if checksum fails
      - run: ./bootstrap
      - save_cache:
          key: R-{{ checksum "bootstrap.R" }}
          paths:
            - packages
      - run: ./test