#!/usr/bin/env bash
here=$(dirname "$0")

mkdir -p packages
if [ -z ${GITHUB_PAT+x} ]; then
    if [ ! -f $PWD/github_token ]; then
        echo "Please go to your GitHub account, click Developer Settings, and generate"
        echo "a new access token with full access to your private repos. Save this"
        echo "token in a file named 'github_token' in the root of this repo."
        exit 1;
    fi
    export GITHUB_PAT=$(<$PWD/github_token)
fi
export R_LIBS_USER="packages"
$here/bootstrap.R
