#!/usr/bin/env bash
rm -r selenium_files
rm -r selenium_screenshots
set -e

# Start shiny APP
SHINY90_QUIET=TRUE SHINY90_TEST_MODE=TRUE ./run.R &
SHINY_PID="$!"

# Start selenium server
echo "Starting selenium server..."
SELENIUM_VERSION=3.9.1
SELENIUM_FILE=selenium-server-standalone-$SELENIUM_VERSION.jar
if [ ! -f "$SELENIUM_FILE" ]; then
    wget http://selenium-release.storage.googleapis.com/3.9/$SELENIUM_FILE
fi
nohup java -jar $SELENIUM_FILE > /dev/null 2>&1 &
SELENIUM_PID="$!"

function cleanup {
    set +e
    echo "Cleaning up..."
    kill $SHINY_PID
    kill $SELENIUM_PID
}
trap cleanup exit INT TERM

#$PWD/src/tests/unittest.R
sleep 5
$PWD/src/tests/test.R